// <auto-generated />
namespace CourseManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create201911260938 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create201911260938));
        
        string IMigrationMetadata.Id
        {
            get { return "201911260139076_Create201911260938"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
